### PR TITLE
Epic/bookings

### PR DESCRIPTION
**Pull request by manlopalm**

### CODE REVIEW

**Review by estefaniagan — APPROVED** [review]

**Review by bencrealc — APPROVED** [review]
No problems detected

**Comment by carcabcol** [comment]
The _no-concurrent bookings_ validation is working fine, but it validates it as if the pet hotel has only one room. It does not allow to make make reservations for different pets in the same day. 

I don't know if that is the expected behavior.

PSG2-Petclinic-bookings

PSG2-Petclinic-new-booking-validation

**Comment by carcabcol** [comment]
Everything is working as expected.

**Review by carcabcol — COMMENTED** [review]
Everything is working as expected.

**Review by carcabcol — APPROVED** [review]
Everything is working as expected.

**Pull request merged**
